<?php

return array(

    'DB_HOST' => $_SERVER['PAXIFI_DB_HOST'],

    'DB_PORT' => $_SERVER['PAXIFI_DB_PORT'],

    'DB_NAME' => $_SERVER['PAXIFI_DB_NAME'],

    'DB_USER' => $_SERVER['PAXIFI_DB_USER'],

    'DB_PASS' => $_SERVER['PAXIFI_DB_PASS'],

    'DEBUG'   => $_SERVER['PAXIFI_DEBUG'],

    'SECURE'   => $_SERVER['PAXIFI_SECURE'],

    'PAYPAL_MODE' => $_SERVER['PAYPAL_MODE'],

    'PAYPAL_URL' => $_SERVER['PAYPAL_URL'],

    'PAYPAL_CLIENT_ID' => $_SERVER['PAYPAL_CLIENT_ID'],

    'PAYPAL_CLIENT_SECRET' => $_SERVER['PAYPAL_CLIENT_SECRET'],

    'PAYPAL_BUSINESS_ACCOUNT' => $_SERVER['PAYPAL_BUSINESS_ACCOUNT'],

    'CLOUDFRONT_URL' => $_SERVER['CLOUDFRONT_URL'],

    'AWS_ACCESS_KEY_ID' => $_SERVER['AWS_ACCESS_KEY'],

    'AWS_SECRET_KEY' => $_SERVER['AWS_SECRET'],

    'AWS_S3_BUCKET' => $_SERVER['AWS_S3_BUCKET'],

    'STRIPE_SECRET_KEY' => $_SERVER['STRIPE_SECRET_KEY'],

    'STRIPE_PUBLISHABLE_KEY' => $_SERVER['STRIPE_PUBLISHABLE_KEY'],

    'STRIPE_CLIENT_ID' => $_SERVER['STRIPE_CLIENT_ID'],

    'STRIPE_CONNECT_API' => $_SERVER['STRIPE_CONNECT_API'],

    'STRIPE_LIVE_MODE' => $_SERVER['STRIPE_LIVE_MODE'],

    'STRIPE_APPLICATION_FEE_RATE' => $_SERVER['STRIPE_APPLICATION_FEE_RATE'],

    'STRIPE_REDIRECT_URL' => $_SERVER['STRIPE_REDIRECT_URL'],

    'NOTIFICATION_ENV' => $_SERVER['NOTIFICATION_ENV'],

    'NOTIFICATION_APNS_CERTIFICATE' => $_SERVER['NOTIFICATION_APNS_CERTIFICATE'],

    'NOTIFICATION_APNS_PASSPHRASE' => $_SERVER['NOTIFICATION_APNS_PASSPHRASE'],

    'NOTIFICATION_GCM_APIKEY' => $_SERVER['NOTIFICATION_GCM_APIKEY'],

    'NOTIFICATION_JPUSH_APP_KEY' => $_SERVER['NOTIFICATION_JPUSH_APP_KEY'],

    'NOTIFICATION_JPUSH_MASTER_SECRET' => $_SERVER['NOTIFICATION_JPUSH_MASTER_SECRET'],

    'QUEUE_DRIVER' => $_SERVER['QUEUE_DRIVER'],

    'QUEUE_HOST' => $_SERVER['QUEUE_HOST'],

    'QUEUE_NAME' => $_SERVER['QUEUE_NAME'],
);

