<?php

return array(

    'DB_HOST' => $_SERVER['PAXIFI_DB_HOST'],

    'DB_PORT' => $_SERVER['PAXIFI_DB_PORT'],

    'DB_NAME' => $_SERVER['PAXIFI_DB_NAME'],

    'DB_USER' => $_SERVER['PAXIFI_DB_USER'],

    'DB_PASS' => $_SERVER['PAXIFI_DB_PASS'],

    'DEBUG'   => $_SERVER['PAXIFI_DEBUG'],

    'PAYPAL_MODE' => $_SERVER['PAYPAL_MODE'],

    'PAYPAL_URL' => $_SERVER['PAYPAL_URL'],

    'PAYPAL_CLIENT_ID' => $_SERVER['PAYPAL_CLIENT_ID'],

    'PAYPAL_CLIENT_SECRET' => $_SERVER['PAYPAL_CLIENT_SECRET'],

    'PAYPAL_BUSINESS_ACCOUNT' => $_SERVER['PAYPAL_BUSINESS_ACCOUNT'],

    'CLOUDFRONT_URL' => $_SERVER['CLOUDFRONT_URL'],

    'AWS_ACCESS_KEY_ID' => $_SERVER['AWS_ACCESS_KEY_ID'],

    'AWS_SECRET_KEY' => $_SERVER['AWS_SECRET_KEY'],

    'AWS_S3_BUCKET' => $_SERVER['AWS_S3_BUCKET'],

);
